# Generated by rust2rpm 10
%bcond_without check
%global debug_package %{nil}

%global crate datetime

Name:           rust-%{crate}
Version:        0.4.7
Release:        8%{?dist}
Summary:        Library for date and time formatting and arithmetic

# Upstream license specification: MIT
# https://github.com/rust-datetime/datetime/issues/20
License:        MIT
URL:            https://crates.io/crates/datetime
Source:         %{crates_source}
# Initial patched metadata
# * No windows
# * No redox
# * Drop regex dependency, https://github.com/rust-datetime/datetime/pull/19
# * Bump iso8601 to 0.3, https://github.com/rust-datetime/datetime/pull/24
Patch0:         datetime-fix-metadata.diff
# Really drop regex dependency
Patch1:         0001-drop-regex-from-dependency-set.patch

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Library for date and time formatting and arithmetic.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/
%exclude %{cargo_registry}/%{crate}-%{version}/tests/generate_tests.rb

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.7-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Sun Jul 14 19:18:07 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.7-7
- Regenerate

* Sun Feb 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.7-6
- Update iso8601 to 0.3

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.7-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.7-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.7-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.7-2
- Rebuild for rust-packaging v5

* Tue Nov 21 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.7-1
- Initial package
